# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
