# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181121_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='abc', max_length=20),
        ),
    ]
