# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181122_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
